sudo: false

branches:
  only:
    - master

language: node_js

matrix:
  include:
    - node_js: "8"
      env: COVERALLS=1
    - node_js: "10"

install:
  - npm i -g lerna
  - lerna bootstrap

after_success:
  - if [ "x$COVERALLS" = "x1" ]; then
      npm i coveralls;
      nyc report --reporter=text-lcov | coveralls;
    fi
