version: "{build}"

branches:
  only:
    - master

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install lerna
  - ./node_modules/.bin/lerna bootstrap -- --force

test_script:
  - ./node_modules/.bin/lerna run test

build: off
